Omnicam threading restructuring
ShefBots/piwarsimulator pull request #1
Opened 2024-04-16 18:06 UTC by Blayzeing

changed the way that it handles multithreading (I've also changed the way that the vision system switch works, but I've tried to be faithful to your original architecture)

2024-04-16 20:18 UTC, guruthree requested changes
I have a moderate worry in how it looks like the new vision system argument is ignoring the template of how `--mode simulation` and `--mode control` work. This can be worked around fairly easily.

On the other hand I'm quite concerned about asyncio.

Piwarsimulator is trying to operate in near real-time for control. Every call to sensors is a poll for that reason and everything returns quickly. I know we spoke some about the potential for a server type thing but looking at the changes using asyncio I'm concerned they might have unintended consequences for connection to the real hardware that we might not have time to debug, or even realise they exist until too late. Things like potentially breaking the serial communications protocol by interrupting at the wrong time. I'm not a super experienced Python programmer so I don't know if my fears are grounded, but I'm sure I wouldn't be up to the task of discovering and fixing something like that out on the day. (We also need to bear in mind that the pi is on the order of 5x slower than our desktops so we can't assume that all would be well pseudo-threading with asyncio.)

I think the solution is to write a visionserver that sits in between piwarsimulatior and omnicam. Omnicam reports to the server when there's new data. When the visionserver is polled by piwarsimulator it reports back either there was no new data or it gives the updated data. This server could run on the pi4 no problem on one of the other cores.

I think we really need to do the visionserver (or something) to keep the main loop as tight as possible.

2024-04-16 20:18 UTC, guruthree commented on piwarsimulator.py
> +    from world.WorldRenderer import * # This is now imported up here,
This was intentionally imported later so that if the system failed to connect to the real robot it didn't bother to start up the GUI and quitting happened nicely.

2024-04-16 20:18 UTC, guruthree commented on piwarsimulator.py
> +    def sigint_handler(signal_received, frame):
I'm pretty sure the sigint handler is now broken

```
^CSIGINT or CTRL-C detected
Caught error: name 'ctrlc_count' is not defined
Traceback (most recent call last):
  File "/home/fcs/Desktop/temp/piwarsimulator/piwarsimulator.py", line 391, in main_loop
    renderer.update(
  File "/home/fcs/Desktop/temp/piwarsimulator/world/WorldRenderer.py", line 115, in update
    self.plot_outline(
  File "/home/fcs/Desktop/temp/piwarsimulator/world/WorldRenderer.py", line 274, in plot_outline
    pygame.draw.aalines(self.screen, color, True, pnts)
  File "/home/fcs/Desktop/temp/piwarsimulator/piwarsimulator.py", line 162, in sigint_handler
    ctrlc_count += 1
    ^^^^^^^^^^^
NameError: name 'ctrlc_count' is not defined
```

2024-04-16 20:18 UTC, guruthree commented on piwarsimulator.py
> +    help="Which vision system to use. 'simple' uses simple vision. 'simulated360' simulates perfect 360 vision. 'socketed360-*' connects to a socket either running at localhost or the protocol-define
Arguments should only be used to change the type of system 360 or forward facing. socketed360- is something that should be inferred by the choice of  --mode control. If we need to use the real sensors inputs that should be through --mode control_simulation.

Arguments should also have _ not - as the separator.

2024-04-16 20:18 UTC, guruthree commented on piwarsimulator.py
> +    help="Which vision system to use. 'simple' uses simple vision. 'simulated360' simulates perfect 360 vision. 'socketed360-*' connects to a socket either running at localhost or the protocol-define
(If something like this is a work around just for testing we need to be more clear about what's happening with that and add comments in the code to the effect of it'll be changed later.)

2024-04-16 20:18 UTC, guruthree commented on piwarsimulator.py
> -    util.import_serial()
What happened to the util.import_serial() calls? Without these the real hardware won't work.

2024-04-16 20:18 UTC, guruthree commented on piwarsimulator.py
> +                from sensors.Vision360 import Vision360 as SimulatedVision
`from sensors.Vision360 import Vision360 as SimulatedVision` suggests the real system is simulated?

Related to my comments about --mode vs --vision-mode?

2024-04-16 20:18 UTC, guruthree commented on piwarsimulator.py
> +        # TODO fake control hardware, real sensors
The real sensor system should be being attached to the robot here.

2024-04-16 20:18 UTC, guruthree commented on piwarsimulator.py
> +    await asyncio.sleep(1) # Wait for things to settle (terrifying)
This wait is mostly for the graphical window to spawn

2024-04-16 20:18 UTC, guruthree commented on sensors/Vision360.py
> +                data= await self.websocket.recv()
Am I reading this correctly that the piwarsimulator program is now listening on a port? Or is this still for going out to make a connection? Or it's formed a connection and is constantly waiting to recv data on that connection whenever the other side is going to send it?

I'm really concerned about the asyncio code interrupting something time critical - a serial transmission to the motor driver board, a decision to not crash into a wall, etc.

2024-04-16 20:39 UTC, guruthree commented
From https://pypi.org/project/websockets/

```#!/usr/bin/env python

from websockets.sync.client import connect

def hello():
    with connect("ws://localhost:8765") as websocket:
        websocket.send("Hello world!")
        message = websocket.recv()
        print(f"Received: {message}")

hello()```

Looks like there's a version of websockets using threading under the hood which I would be much happier running as that's I think more tested on the real hardware.

2024-04-17 02:20 UTC, Blayzeing commented
Closing, will submit threading-based implementation.
Technically, I think the asyncio approach has a better chance of not messing up timings on stuff due to it not using the GIL, but the threading approach was nice enough to work with anyhow and I've made it quite a bit more robust.

2024-04-17 02:20 UTC, closed without merging